"""add analytics columns to clicks

Revision ID: 146f0a4dbd1b
Revises: ab0209f91a56
Create Date: 2026-05-08 01:14:57.947701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146f0a4dbd1b'
down_revision: Union[str, Sequence[str], None] = 'ab0209f91a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('visitor_id', sa.String(), nullable=True))
    op.add_column('clicks', sa.Column('device_os', sa.String(), nullable=True))
    op.add_column('clicks', sa.Column('country', sa.String(), nullable=True))
    op.add_column('clicks', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('clicks', sa.Column('city', sa.String(), nullable=True))
    op.create_index(op.f('ix_clicks_visitor_id'), 'clicks', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_visitor_id'), table_name='clicks')
    op.drop_column('clicks', 'city')
    op.drop_column('clicks', 'country_code')
    op.drop_column('clicks', 'country')
    op.drop_column('clicks', 'device_os')
    op.drop_column('clicks', 'visitor_id')
    # ### end Alembic commands ###
