"""short_code nullable

Revision ID: 4c857cc3bc64
Revises: 078e8124cb91
Create Date: 2026-09-23 19:58:13.474170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c857cc3bc64'
down_revision: Union[str, Sequence[str], None] = '078e8124cb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
