"""add referrer column

Revision ID: ab84f1dd1bf6
Revises: 146f0a4dbd1b
Create Date: 2026-05-20 19:54:44.199548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab84f1dd1bf6'
down_revision: Union[str, Sequence[str], None] = '146f0a4dbd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('referrer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'referrer')
    # ### end Alembic commands ###
