"""add composite index on clicks url_id timestamp

Revision ID: eadb36e05a46
Revises: ab84f1dd1bf6
Create Date: 2026-09-20 21:08:52.310998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadb36e05a46'
down_revision: Union[str, Sequence[str], None] = 'ab84f1dd1bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_clicls_url_id_timestamp', 'clicks', ['url_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clicls_url_id_timestamp', table_name='clicks')
    # ### end Alembic commands ###
